resume_from_checkpoint_path: None
pretrained_model_name_or_path: 'naver-clova-ix/donut-base'
dataset_name_or_paths: 
  - '/home/ahsenmailbox/Desktop/22-04-2023/donut/data'
sort_json_key: False
train_batch_sizes: 
  - 1
val_batch_sizes: 
  - 1
input_size: 
  - 1280
  - 960
max_length: 768
align_long_axis: False
num_nodes: 1
seed: 2022
lr: 3e-05
warmup_steps: 30
num_training_samples_per_epoch: 5
max_epochs: 30
max_steps: -1
num_workers: 1
val_check_interval: 1.0
check_val_every_n_epoch: 3
gradient_clip_val: 1.0
verbose: False
save_path: '/home/ahsenmailbox/Desktop/22-04-2023/donut/model'